# https://www.onlinetutorialspoint.com/spring-boot/spring-boot-jndi-configuration-external-tomcat.html
# To set the Environment Variables in Tomcat use the link below
# https://myupbeat.wordpress.com/2013/03/07/spring-profiles-and-tomcat/
spring:
  datasource:
    # https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-sql.html
    jndi-name: java:comp/env/jdbc/jndi
  jpa:
    # This is there since I am using MySQL in my JNDI configuration
    mapping-resources:
      - db/orm/mysql-orm.xml
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        ddl-auto: validate