# Disable Liquibase for MongoDB
# https://stackoverflow.com/questions/37708145/spring-boot-disable-liquibase-at-startup
spring:
  liquibase:
    enabled: false
  data:
    # https://www.codementor.io/gtommee97/rest-api-java-spring-boot-and-mongodb-j7nluip8d
    # https://www.djamware.com/post/5b2f000880aca77b083240b2/spring-boot-security-and-data-mongodb-authentication-example
    # use https://docs.mongodb.com/manual/reference/method/db.createUser/ to create the database
    # https://www.baeldung.com/spring-data-mongodb-guide
    mongodb:
      host: localhost
      port: 27017
      database: springmongodb